// <auto-generated />
namespace FitDiary.SecuredApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Lessinusertemporary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lessinusertemporary));
        
        string IMigrationMetadata.Id
        {
            get { return "201705251134376_Less in user temporary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
